# Generated by Django 4.2 on 2024-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_remove_productgroup_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crudlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
        ),
    ]
