# Generated by Django 4.2 on 2024-07-21 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfccard",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "URL",
                "verbose_name_plural": "URLs",
            },
        ),
    ]
