# Generated by Django 4.2 on 2024-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_alter_nfccard_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfccard",
            name="password",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Password"
            ),
        ),
    ]
