# Generated by Django 4.2 on 2024-07-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0003_nfccard_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfccard",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
