# Generated by Django 4.2 on 2024-07-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0004_nfccard_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfccard",
            name="title",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Title"
            ),
        ),
    ]
